# ArgoCD App: Gateway Configuration
# @author Shanaka Jayasundera - shanakaj@gmail.com
#
# LAYER 3: K8s Customizations
# Sync Wave: 2 (after Kong is deployed)
# Deploys GatewayClass and Gateway resources

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gateway-config
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/shanaka-versent/EKS-Kong-GatewayAPI-Demo.git
    targetRevision: HEAD
    path: k8s/kong
    directory:
      include: "{gateway-class.yaml,gateway.yaml,prometheus-plugin.yaml}"

  destination:
    server: https://kubernetes.default.svc
    namespace: kong

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
